{
    "name": "Sibic Inventaire D'actifs",
    "version": "17.0.1.0",
    "description": "",
    "summary": "",
    "category": "",
    "author": "Sibic, Rachid Benrabia",
    "depends": [
        "base",
        "mail",
        "stock",
    ],
    "data": [
        "data/sequence.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/equipe_inventaire_view.xml",
        "views/inventaire_global_view.xml",
        "views/sous_inventaire.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "auto-install": False,
    "application": True,
}
